export const DEPARTAMENTOS_COLOMBIA = [
  "Amazonas",
  "Antioquia",
  "Arauca",
  "Atlántico",
  "Bogotá D.C.",
  "Bolívar",
  "Boyacá",
  "Caldas",
  "Caquetá",
  "Casanare",
  "Cauca",
  "Cesar",
  "Chocó",
  "Córdoba",
  "Cundinamarca",
  "Guainía",
  "Guaviare",
  "Huila",
  "La Guajira",
  "Magdalena",
  "Meta",
  "Nariño",
  "Norte de Santander",
  "Putumayo",
  "Quindío",
  "Risaralda",
  "San Andrés y Providencia",
  "Santander",
  "Sucre",
  "Tolima",
  "Valle del Cauca",
  "Vaupés",
  "Vichada",
];

// Ciudades/municipios principales por departamento. No es exhaustivo (Colombia
// tiene más de 1.100 municipios); incluye los más relevantes de cada uno.
// Si no encuentras el municipio exacto, puedes escribir "Otra" y digitarlo.
export const CIUDADES_POR_DEPARTAMENTO: Record<string, string[]> = {
  Amazonas: ["Leticia", "Puerto Nariño"],
  Antioquia: [
    "Medellín", "Envigado", "Itagüí", "Bello", "Rionegro", "Sabaneta", "La Ceja",
    "Apartadó", "Turbo", "Caucasia", "Copacabana", "Girardota", "Marinilla",
    "El Retiro", "Guarne", "Santa Rosa de Osos", "Yarumal", "Andes", "Segovia",
  ],
  Arauca: ["Arauca", "Saravena", "Tame", "Arauquita"],
  Atlántico: ["Barranquilla", "Soledad", "Malambo", "Puerto Colombia", "Sabanalarga", "Galapa"],
  "Bogotá D.C.": ["Bogotá"],
  Bolívar: ["Cartagena", "Magangué", "Turbaco", "Arjona", "El Carmen de Bolívar"],
  Boyacá: ["Tunja", "Duitama", "Sogamoso", "Chiquinquirá", "Paipa", "Villa de Leyva"],
  Caldas: ["Manizales", "La Dorada", "Chinchiná", "Villamaría", "Riosucio"],
  Caquetá: ["Florencia", "San Vicente del Caguán", "Puerto Rico"],
  Casanare: ["Yopal", "Aguazul", "Villanueva", "Tauramena"],
  Cauca: ["Popayán", "Santander de Quilichao", "Puerto Tejada", "El Bordo"],
  Cesar: ["Valledupar", "Aguachica", "Codazzi", "La Jagua de Ibirico"],
  Chocó: ["Quibdó", "Istmina", "Condoto"],
  Córdoba: ["Montería", "Lorica", "Cereté", "Sahagún", "Planeta Rica"],
  Cundinamarca: [
    "Soacha", "Chía", "Zipaquirá", "Facatativá", "Fusagasugá", "Girardot",
    "Mosquera", "Madrid", "Funza", "Cajicá", "Cota", "La Calera", "Tenjo",
  ],
  Guainía: ["Inírida"],
  Guaviare: ["San José del Guaviare"],
  Huila: ["Neiva", "Pitalito", "Garzón", "La Plata"],
  "La Guajira": ["Riohacha", "Maicao", "Uribia", "Fonseca"],
  Magdalena: ["Santa Marta", "Ciénaga", "Fundación", "El Banco"],
  Meta: ["Villavicencio", "Acacías", "Granada", "Puerto López"],
  Nariño: ["Pasto", "Ipiales", "Tumaco", "Túquerres"],
  "Norte de Santander": ["Cúcuta", "Ocaña", "Villa del Rosario", "Pamplona"],
  Putumayo: ["Mocoa", "Puerto Asís", "Orito"],
  Quindío: ["Armenia", "Calarcá", "Montenegro", "La Tebaida", "Circasia"],
  Risaralda: ["Pereira", "Dosquebradas", "Santa Rosa de Cabal", "La Virginia"],
  "San Andrés y Providencia": ["San Andrés", "Providencia"],
  Santander: ["Bucaramanga", "Floridablanca", "Girón", "Piedecuesta", "Barrancabermeja", "San Gil"],
  Sucre: ["Sincelejo", "Corozal", "Sampués"],
  Tolima: ["Ibagué", "Espinal", "Melgar", "Honda", "Chaparral"],
  "Valle del Cauca": [
    "Cali", "Palmira", "Buenaventura", "Tuluá", "Cartago", "Buga",
    "Jamundí", "Yumbo", "Candelaria", "Florida", "Zarzal",
  ],
  Vaupés: ["Mitú"],
  Vichada: ["Puerto Carreño"],
};
