/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as ReembolsosRouteImport } from './routes/reembolsos'
import { Route as ProveedoresRouteImport } from './routes/proveedores'
import { Route as NuevoRouteImport } from './routes/nuevo'
import { Route as MovimientosRouteImport } from './routes/movimientos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContabilidadRouteImport } from './routes/contabilidad'
import { Route as ConfiguracionRouteImport } from './routes/configuracion'
import { Route as ConceptosRouteImport } from './routes/conceptos'
import { Route as IndexRouteImport } from './routes/index'

const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const ReembolsosRoute = ReembolsosRouteImport.update({
  id: '/reembolsos',
  path: '/reembolsos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProveedoresRoute = ProveedoresRouteImport.update({
  id: '/proveedores',
  path: '/proveedores',
  getParentRoute: () => rootRouteImport,
} as any)
const NuevoRoute = NuevoRouteImport.update({
  id: '/nuevo',
  path: '/nuevo',
  getParentRoute: () => rootRouteImport,
} as any)
const MovimientosRoute = MovimientosRouteImport.update({
  id: '/movimientos',
  path: '/movimientos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContabilidadRoute = ContabilidadRouteImport.update({
  id: '/contabilidad',
  path: '/contabilidad',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracionRoute = ConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => rootRouteImport,
} as any)
const ConceptosRoute = ConceptosRouteImport.update({
  id: '/conceptos',
  path: '/conceptos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conceptos': typeof ConceptosRoute
  '/configuracion': typeof ConfiguracionRoute
  '/contabilidad': typeof ContabilidadRoute
  '/login': typeof LoginRoute
  '/movimientos': typeof MovimientosRoute
  '/nuevo': typeof NuevoRoute
  '/proveedores': typeof ProveedoresRoute
  '/reembolsos': typeof ReembolsosRoute
  '/usuarios': typeof UsuariosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conceptos': typeof ConceptosRoute
  '/configuracion': typeof ConfiguracionRoute
  '/contabilidad': typeof ContabilidadRoute
  '/login': typeof LoginRoute
  '/movimientos': typeof MovimientosRoute
  '/nuevo': typeof NuevoRoute
  '/proveedores': typeof ProveedoresRoute
  '/reembolsos': typeof ReembolsosRoute
  '/usuarios': typeof UsuariosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/conceptos': typeof ConceptosRoute
  '/configuracion': typeof ConfiguracionRoute
  '/contabilidad': typeof ContabilidadRoute
  '/login': typeof LoginRoute
  '/movimientos': typeof MovimientosRoute
  '/nuevo': typeof NuevoRoute
  '/proveedores': typeof ProveedoresRoute
  '/reembolsos': typeof ReembolsosRoute
  '/usuarios': typeof UsuariosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/conceptos'
    | '/configuracion'
    | '/contabilidad'
    | '/login'
    | '/movimientos'
    | '/nuevo'
    | '/proveedores'
    | '/reembolsos'
    | '/usuarios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/conceptos'
    | '/configuracion'
    | '/contabilidad'
    | '/login'
    | '/movimientos'
    | '/nuevo'
    | '/proveedores'
    | '/reembolsos'
    | '/usuarios'
  id:
    | '__root__'
    | '/'
    | '/conceptos'
    | '/configuracion'
    | '/contabilidad'
    | '/login'
    | '/movimientos'
    | '/nuevo'
    | '/proveedores'
    | '/reembolsos'
    | '/usuarios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConceptosRoute: typeof ConceptosRoute
  ConfiguracionRoute: typeof ConfiguracionRoute
  ContabilidadRoute: typeof ContabilidadRoute
  LoginRoute: typeof LoginRoute
  MovimientosRoute: typeof MovimientosRoute
  NuevoRoute: typeof NuevoRoute
  ProveedoresRoute: typeof ProveedoresRoute
  ReembolsosRoute: typeof ReembolsosRoute
  UsuariosRoute: typeof UsuariosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reembolsos': {
      id: '/reembolsos'
      path: '/reembolsos'
      fullPath: '/reembolsos'
      preLoaderRoute: typeof ReembolsosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proveedores': {
      id: '/proveedores'
      path: '/proveedores'
      fullPath: '/proveedores'
      preLoaderRoute: typeof ProveedoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nuevo': {
      id: '/nuevo'
      path: '/nuevo'
      fullPath: '/nuevo'
      preLoaderRoute: typeof NuevoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movimientos': {
      id: '/movimientos'
      path: '/movimientos'
      fullPath: '/movimientos'
      preLoaderRoute: typeof MovimientosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contabilidad': {
      id: '/contabilidad'
      path: '/contabilidad'
      fullPath: '/contabilidad'
      preLoaderRoute: typeof ContabilidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracion': {
      id: '/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof ConfiguracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conceptos': {
      id: '/conceptos'
      path: '/conceptos'
      fullPath: '/conceptos'
      preLoaderRoute: typeof ConceptosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConceptosRoute: ConceptosRoute,
  ConfiguracionRoute: ConfiguracionRoute,
  ContabilidadRoute: ContabilidadRoute,
  LoginRoute: LoginRoute,
  MovimientosRoute: MovimientosRoute,
  NuevoRoute: NuevoRoute,
  ProveedoresRoute: ProveedoresRoute,
  ReembolsosRoute: ReembolsosRoute,
  UsuariosRoute: UsuariosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
